# Generated by Django 3.0 on 2020-09-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200923_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayFortCallbackTransactionDetails',
        ),
        migrations.RemoveField(
            model_name='payforttransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='PayFortTransactionResponse',
        ),
        migrations.AlterUniqueTogether(
            name='verifyusertransaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='verifyusertransaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='PayFortTransaction',
        ),
        migrations.DeleteModel(
            name='VerifyUserTransaction',
        ),
    ]
