# Generated by Django 3.0 on 2020-09-19 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(default=None, max_length=11)),
                ('zipcode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('state', localflavor.us.models.USStateField(default=None, max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=users.models.profile_image)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('last_accessed_on', models.DateTimeField()),
                ('mobile_verification_status', models.BooleanField(default=False)),
                ('email_verification_status', models.BooleanField(default=False)),
                ('address', models.TextField(default=None, max_length=400)),
                ('termsconditions', models.BooleanField(default=False)),
                ('remember_me', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=users.models.temp_profile_image)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(default=None, max_length=11)),
                ('zipcode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('state', localflavor.us.models.USStateField(default=None, max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=users.models.profile_image)),
                ('mobile_token', models.CharField(max_length=4)),
                ('email_token', models.CharField(max_length=50, null=True)),
                ('created_on_mobile', models.DateTimeField()),
                ('created_on_email', models.DateTimeField()),
                ('email_verification_status', models.BooleanField(default=False)),
                ('mobile_verification_status', models.BooleanField(default=False)),
                ('address', models.TextField(default=None, max_length=400)),
                ('termsconditions', models.BooleanField(default=False)),
                ('remember_me', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_token', models.CharField(blank=True, max_length=4, null=True)),
                ('email_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on_mobile', models.DateTimeField(blank=True, null=True)),
                ('created_on_email', models.DateTimeField(blank=True, null=True)),
                ('mobile_verification_status', models.BooleanField(default=False)),
                ('email_verification_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
